//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class asm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal asm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Resources.asm", typeof(asm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Generated by z64rasm
        ///; commit: 9e677860034abaf9584e16c291fb5a549ea7edc0
        ///10,ff6f239f
        ///14,ebb8425f
        ///20580,3800000
        ///20584,3860000
        ///20588,3800000
        ///2058c,0
        ///20590,0
        ///20594,0
        ///20598,0
        ///2059c,0
        ///205a0,0
        ///205a4,0
        ///205a8,0
        ///205ac,0
        ///205b0,0
        ///205b4,0
        ///205b8,0
        ///205bc,0
        ///205c0,0
        ///205c4,0
        ///205c8,0
        ///205cc,0
        ///205d0,0
        ///205d4,0
        ///205d8,0
        ///205dc,0
        ///205e0,0
        ///205e4,0
        ///205e8,0
        ///205ec,0
        ///b3c994,c1c9933
        ///b3c998,0
        ///b3c99c,8603001c
        ///b3c9a4,0
        ///b3d6c8,c1c991d
        ///b4cea8,afa40018
        ///b4ceac,c1c800f
        ///b4ceb0,afa5001c
        ///b4ceb4,0
        ///b66b6c,c1c8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rom_patch {
            get {
                return ResourceManager.GetString("rom_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;DPAD_CONFIG&quot;: &quot;03809430&quot;,
        ///    &quot;DPAD_TEXTURE&quot;: &quot;0380A900&quot;,
        ///    &quot;EXT_MSG_DATA_FILE&quot;: &quot;03809C04&quot;,
        ///    &quot;EXT_MSG_TABLE&quot;: &quot;0380A520&quot;,
        ///    &quot;EXT_MSG_TABLE_COUNT&quot;: &quot;03809BCC&quot;,
        ///    &quot;EXT_OBJECTS&quot;: &quot;03809C20&quot;,
        ///    &quot;FONT_TEXTURE&quot;: &quot;0380B900&quot;,
        ///    &quot;G_C_HEAP&quot;: &quot;03820000&quot;,
        ///    &quot;G_PAYLOAD_ADDR&quot;: &quot;03800000&quot;,
        ///    &quot;HASH_ICONS&quot;: &quot;038094BC&quot;,
        ///    &quot;HUD_COLOR_CONFIG&quot;: &quot;03809590&quot;,
        ///    &quot;ITEM_OVERRIDE_COUNT&quot;: &quot;03809B88&quot;,
        ///    &quot;ITEM_OVERRIDE_ENTRIES&quot;: &quot;03809CA0&quot;,
        ///    &quot;MISC_CONFIG&quot;: &quot;038099C8&quot;,
        ///    &quot;MMR_CONFIG&quot;: &quot;03 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string symbols {
            get {
                return ResourceManager.GetString("symbols", resourceCulture);
            }
        }
    }
}
