//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class asm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal asm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Resources.asm", typeof(asm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Generated by z64rasm
        ///; commit: fa08d32a4481aa96581e34a0cef381eb56ab2530
        ///10,ff6f239f
        ///14,ebb8425f
        ///20580,3800000
        ///20584,3860000
        ///20588,3800000
        ///2058c,0
        ///20590,0
        ///20594,0
        ///20598,0
        ///2059c,0
        ///205a0,0
        ///205a4,0
        ///205a8,0
        ///205ac,0
        ///205b0,0
        ///205b4,0
        ///205b8,0
        ///205bc,0
        ///205c0,0
        ///205c4,0
        ///205c8,0
        ///205cc,0
        ///205d0,0
        ///205d4,0
        ///205d8,0
        ///205dc,0
        ///205e0,0
        ///205e4,0
        ///205e8,0
        ///205ec,0
        ///b3d6c8,c1c9458
        ///b4cea8,afa40018
        ///b4ceac,c1c800f
        ///b4ceb0,afa5001c
        ///b4ceb4,0
        ///b66b6c,c1c8283
        ///b66b70,8463f6a6
        ///b66b78,0
        ///b66ba8,1000001f
        ///b66b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rom_patch {
            get {
                return ResourceManager.GetString("rom_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;DPAD_CONFIG&quot;: &quot;03806E3C&quot;,
        ///    &quot;DPAD_TEXTURE&quot;: &quot;03807368&quot;,
        ///    &quot;EXT_OBJECTS&quot;: &quot;038070A8&quot;,
        ///    &quot;G_C_HEAP&quot;: &quot;03820000&quot;,
        ///    &quot;G_PAYLOAD_ADDR&quot;: &quot;03800000&quot;,
        ///    &quot;HASH_ICONS&quot;: &quot;03806EC8&quot;,
        ///    &quot;HUD_COLOR_CONFIG&quot;: &quot;03806F58&quot;,
        ///    &quot;MISC_CONFIG&quot;: &quot;0380701C&quot;,
        ///    &quot;PAYLOAD_END&quot;: &quot;03808370&quot;,
        ///    &quot;PAYLOAD_START&quot;: &quot;03800000&quot;,
        ///    &quot;SAVE_FILE_CONFIG&quot;: &quot;0380704C&quot;,
        ///    &quot;dpad_sprite&quot;: &quot;03806F48&quot;,
        ///    &quot;g_external_effects&quot;: &quot;03806E58&quot;,
        ///    &quot;heap_next&quot;: &quot;038070A0&quot;,
        ///    &quot;setup_db&quot;: &quot;03806F20&quot;
        ///}
        ///.
        /// </summary>
        internal static string symbols {
            get {
                return ResourceManager.GetString("symbols", resourceCulture);
            }
        }
    }
}
