//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class skulltula {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal skulltula() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Randomizer.Resources.skulltula", typeof(skulltula).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Scenes&quot;: [{&quot;Index&quot;: 20, &quot;Name&quot;: &quot;Deku Palace&quot;, &quot;Spiders&quot;: [{&quot;Name&quot;: &quot;Deku Palace Garden - Between Torches&quot;, &quot;Room&quot;: 2, &quot;Path&quot;: [[65230, 45, 1068]]}]}, {&quot;Index&quot;: 99, &quot;Name&quot;: &quot;Clock Tower Interior&quot;, &quot;Spiders&quot;: [{&quot;Name&quot;: &quot;Clock Tower Interior - Wall Around Entrance Door&quot;, &quot;Description&quot;: &quot;Crawls next to and above entrance door.&quot;, &quot;Path&quot;: [[120, 17, 270], [120, 217, 270], [65481, 217, 270]]}, {&quot;Name&quot;: &quot;Clock Tower Interior - Behind Waterwheel&quot;, &quot;Description&quot;: &quot;Crawls behind wall used by waterwheel.&quot;, &quot;Path&quot;: [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spiders {
            get {
                return ResourceManager.GetString("spiders", resourceCulture);
            }
        }
    }
}
